### PR TITLE
Copying generator content to internal datastore

### LINKED ISSUE #13: Bug: Library does not work with all `Iterable<Quad>` types
In the following example where a generator function is used, the normalized dataset has size `0` when size `1` is expected.

```ts
import * as n3  from 'n3';
import * as rdf from '@rdfjs/types';
import {RDFC10, Quads, InputQuads } from 'rdfjs-c14n';

function *createYourQuads(): Iterable<rdf.Quad> {
    yield n3.DataFactory.quad(
        n3.DataFactory.namedNode('http://example.org/subject'),
        n3.DataFactory.namedNode('http://example.org/predicate'),
        n3.DataFactory.literal('object')
    );
}

async function main() {
    const rdfc10 = new RDFC10(n3.DataFactory);  
    const input: InputQuads = createYourQuads();
    const normalized: Quads = (await rdfc10.c14n(input)).canonicalized_dataset;
    console.log('Normalized dataset size:', normalized.size);
}

main()
```

### PR DESCRIPTION
**Pull request by iherman**
The problem leading to #13 is that a generator cannot be used twice, and the algorithm does go through the internal dataset several times. I.e., the input data must be copied into an internal store (much like doing it to avoid duplicate quads).

The approach on whether doing a copy or not has been slightly changed. It can be user controlled (optionally); in the absence of that control, a copy is done _unless_ the input implements the `rdf.DatasetCore` interface.

Fix #13

cc @jeswr

### CODE REVIEW

File: lib/canonicalization.ts [hunk 1]
```diff
@@ -48,21 +49,27 @@ const createBidMap = (graph: Quads): ReadonlyMap<rdf.BlankNode, BNodeId> => {
...
+            const createCopy = (): InputQuads => {
+                const retval = new n3.Store();
+                for (const quad of input) retval.add(quad);
+                return retval;
+            };
+            if (copy === undefined) {
+                return isQuads(input) ? input : createCopy();
+            } else {
+                return copy ? createCopy() : input;
+            }
```
Comment (jeswr) [inline lib/canonicalization.ts]:
```suggestion
            if (copy ?? !isQuads(input)) {
                const retval = new n3.Store();
                for (const quad of input) retval.add(quad);
                return retval;
            }  
            return input;
```

Note that `??` is the Nullish coalescing operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

**Review by jeswr — APPROVED** [review]
